name: Release staging

on:
    push:
        tags:
            - staging/*

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Build for staging
              run: echo "Building for staging ..."

    deploy:
        runs-on: ubuntu-latest
        
        steps:
            - name: Deploy on staging
              run: echo "Deploying on staging ..."