name: Release production

on:
    push:
        tags:
            - production/*

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Build for production
              run: echo "Building for production ..."

    deploy:
        runs-on: ubuntu-latest
        
        steps:
            - name: Deploy on production
              run: echo "Deploying on production ..."